In [ ]:
arrow::read_parquet(here("data", "atpRaw.parquet"), as_data_frame = TRUE) -> atp

In [ ]:
(atp %>% 
    separate_wider_delim(Date, " - ", names=c("ds", "df"), too_few = "debug") %>%
    select(ds, df, Date, Date_ok, Date_pieces, Date_remainder) -> atpD.debug)

Warning message:
"Debug mode activated: adding variables `Date_ok`, `Date_pieces`, and `Date_remainder`."

        ds         df         Date                    Date_ok Date_pieces
1       2021.11.22 2021.12.05 2021.11.22 - 2021.12.05 TRUE    2
2       2022.02.21 2022.02.26 2022.02.21 - 2022.02.26 TRUE    2
3       2021.11.15 2021.11.21 2021.11.15 - 2021.11.21 TRUE    2
4       2021.11.15 2021.11.21 2021.11.15 - 2021.11.21 TRUE    2
5       2021.11.01 2021.11.07 2021.11.01 - 2021.11.07 TRUE    2
6       2021.11.01 2021.11.07 2021.11.01 - 2021.11.07 TRUE    2
7       2021.11.15 2021.11.21 2021.11.15 - 2021.11.21 TRUE    2
8       2021.11.22 2021.12.05 2021.11.22 - 2021.12.05 TRUE    2
9       2022.02.21 2022.02.26 2022.02.21 - 2022.02.26 TRUE    2
10      2022.02.21 2022.02.26 2022.02.21 - 2022.02.26 TRUE    2
11      2021.11.22 2021.12.05 2021.11.22 - 2021.12.05 TRUE    2
12      2021.11.15 2021.11.21 2021.11.15 - 2021.11.21 TRUE    2
13      2021.11.22 2021.12.05 2021.11.22 - 2021.12.05 TRUE    2
14      2021.08.30 2021.09.12 2021.08.30 - 2021.09.12 TRUE    2
15      2021.08.30 2021.09.12 2021.08.30 - 2021.09.12 TRUE    2
16      2021.08.30 2021.09.12 2021.08.30 - 2021.09.12 TRUE    2
17      2021.08.30 2021.09.12 2021.08.30 - 2021.09.12 TRUE    2
18      2021.11.01 2021.11.07 2021.11.01 - 2021.11.07 TRUE    2
19      2021.07.26 2021.08.01 2021.07.26 - 2021.08.01 TRUE    2
20      2021.07.26 2021.08.01 2021.07.26 - 2021.08.01 TRUE    2
21      2021.11.01 2021.11.07 2021.11.01 - 2021.11.07 TRUE    2
22      2021.11.01 2021.11.07 2021.11.01 - 2021.11.07 TRUE    2
23      2021.08.30 2021.09.12 2021.08.30 - 2021.09.12 TRUE    2
24      2021.08.30 2021.09.12 2021.08.30 - 2021.09.12 TRUE    2
25      2021.11.01 2021.11.07 2021.11.01 - 2021.11.07 TRUE    2
26      2021.08.30 2021.09.12 2021.08.30 - 2021.09.12 TRUE    2
27      2021.07.26 2021.08.01 2021.07.26 - 2021.08.01 TRUE    2
28      2021.07.26 2021.08.01 2021.07.26 - 2021.08.01 TRUE    2
29      2021.07.26 2021.08.01 2021.07.26 - 2021.08.01 TRUE    2
30      2021.07.26 2021.08.01 2021.07.26 - 2021.08.01 TRUE    2
⋮       ⋮          ⋮          ⋮                       ⋮       ⋮
1308806 2008.08.25 2008.08.31 2008.08.25 - 2008.08.31 TRUE    2
1308807 2008.08.18 2008.08.31 2008.08.18 - 2008.08.31 TRUE    2
1308808 2008.08.25 2008.08.31 2008.08.25 - 2008.08.31 TRUE    2
1308809 2008.06.30 2008.07.06 2008.06.30 - 2008.07.06 TRUE    2
1308810 2008.06.30 2008.07.06 2008.06.30 - 2008.07.06 TRUE    2
1308811 2008.06.30 2008.07.06 2008.06.30 - 2008.07.06 TRUE    2
1308812 2008.04.28 2008.05.04 2008.04.28 - 2008.05.04 TRUE    2
1308813 2008.04.14 2008.04.20 2008.04.14 - 2008.04.20 TRUE    2
1308814 2008.04.14 2008.04.20 2008.04.14 - 2008.04.20 TRUE    2
1308815 2008.04.14 2008.04.20 2008.04.14 - 2008.04.20 TRUE    2
1308816 2008.03.17 2008.03.30 2008.03.17 - 2008.03.30 TRUE    2
1308817 2008.03.17 2008.03.30 2008.03.17 - 2008.03.30 TRUE    2
1308818 2008.02.25 2008.03.02 2008.02.25 - 2008.03.02 TRUE    2
1308819 2008.02.25 2008.03.02 2008.02.25 - 2008.03.02 TRUE    2
1308820 2007.10.08 2007.10.14 2007.10.08 - 2007.10.14 TRUE    2
1308821 2007.10.01 2007.10.07 2007.10.01 - 2007.10.07 TRUE    2
1308822 2007.08.06 2007.08.12 2007.08.06 - 2007.08.12 TRUE    2
1308823 2007.08.06 2007.08.12 2007.08.06 - 2007.08.12 TRUE    2
1308824 2007.04.30 2007.05.06 2007.04.30 - 2007.05.06 TRUE    2
1308825 2007.02.05 2007.02.11 2007.02.05 - 2007.02.11 TRUE    2
1308826 2006.11.20 2006.11.26 2006.11.20 - 2006.11.26 TRUE    2
1308827 2006.11.20 2006.11.26 2006.11.20 - 2006.11.26 TRUE    2
1308828 2006.11.20 2006.11.26 2006.11.20 - 2006.11.26 TRUE    2
1308829 2006.11.20 2006.11.26 2006.11.20 - 2006.11.26 TRUE    2
1308830 2006.10.16 2006.10.22 2006.10.16 - 2006.10.22 TRUE    2
1308831 2006.10.23 2006.10.29 2006.10.23 - 2006.10.29 TRUE    2
1308832 2006.10.16 2006.10.22 2006.10.16 - 2006.10.22 TRUE    2
1308833 2006.10.09 2006.10.15 2006.10.09 - 2006.10.15 TRUE    2
1308834 2006.10.09 2006.10.15 2006.10.09 - 2006.10.15 TRUE    2
1308835 2006.09.18 2006.10.01 2006.09.18 - 2006.10.01 TRUE    2
        Date_remainder
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮       ⋮
1308806
1308807
1308808
1308809
1308810
1308811
1308812
1308813
1308814
1308815
1308816
1308817
1308818
1308819
1308820
1308821
1308822
1308823
1308824
1308825
1308826
1308827
1308828
1308829
1308830
1308831
1308832
1308833
1308834
1308835

TODO analise

In [ ]:
atpD.debug %>% filter(Date_ok == F)

      ds         df Date       Date_ok Date_pieces Date_remainder
1     2011.05.09 NA 2011.05.09 FALSE   1
2     2011.05.09 NA 2011.05.09 FALSE   1
3     2011.05.09 NA 2011.05.09 FALSE   1
4     2011.05.09 NA 2011.05.09 FALSE   1
5     2011.11.21 NA 2011.11.21 FALSE   1
6     2011.11.21 NA 2011.11.21 FALSE   1
7     2011.11.21 NA 2011.11.21 FALSE   1
8     2011.11.21 NA 2011.11.21 FALSE   1
9     2011.11.21 NA 2011.11.21 FALSE   1
10    2011.11.21 NA 2011.11.21 FALSE   1
11    2011.11.21 NA 2011.11.21 FALSE   1
12    2011.11.21 NA 2011.11.21 FALSE   1
13    2011.05.09 NA 2011.05.09 FALSE   1
14    2011.05.16 NA 2011.05.16 FALSE   1
15    2011.11.21 NA 2011.11.21 FALSE   1
16    2002.12.09 NA 2002.12.09 FALSE   1
17    2011.11.21 NA 2011.11.21 FALSE   1
18    2011.11.21 NA 2011.11.21 FALSE   1
19    2011.11.21 NA 2011.11.21 FALSE   1
20    2011.11.21 NA 2011.11.21 FALSE   1
21    2011.11.21 NA 2011.11.21 FALSE   1
22    2011.11.21 NA 2011.11.21 FALSE   1
23    2011.11.21 NA 2011.11.21 FALSE   1
24    2011.11.21 NA 2011.11.21 FALSE   1
25    2011.11.21 NA 2011.11.21 FALSE   1
26    2011.11.21 NA 2011.11.21 FALSE   1
27    2011.11.21 NA 2011.11.21 FALSE   1
28    2011.05.16 NA 2011.05.16 FALSE   1
29    2011.05.16 NA 2011.05.16 FALSE   1
30    2004.12.13 NA 2004.12.13 FALSE   1
⋮     ⋮          ⋮  ⋮          ⋮       ⋮           ⋮
12361 1980.04.07 NA 1980.04.07 FALSE   1
12362 1980.03.31 NA 1980.03.31 FALSE   1
12363 1980.03.03 NA 1980.03.03 FALSE   1
12364 1980.03.03 NA 1980.03.03 FALSE   1
12365 1980.03.03 NA 1980.03.03 FALSE   1
12366 1980.01.21 NA 1980.01.21 FALSE   1
12367 1980.01.21 NA 1980.01.21 FALSE   1
12368 1980.01.21 NA 1980.01.21 FALSE   1
12369 1980.01.21 NA 1980.01.21 FALSE   1
12370 1980.01.14 NA 1980.01.14 FALSE   1
12371 1980.01.14 NA 1980.01.14 FALSE   1
12372 1980.01.14 NA 1980.01.14 FALSE   1
12373 1980.01.14 NA 1980.01.14 FALSE   1
12374 1980.01.14 NA 1980.01.14 FALSE   1
12375 1977.09.17 NA 1977.09.17 FALSE   1
12376 1977.09.17 NA 1977.09.17 FALSE   1
12377 1977.09.17 NA 1977.09.17 FALSE   1
12378 1977.09.17 NA 1977.09.17 FALSE   1
12379 1976.12.19 NA 1976.12.19 FALSE   1
12380 1976.12.19 NA 1976.12.19 FALSE   1
12381 1976.12.19 NA 1976.12.19 FALSE   1
12382 2011.11.21 NA 2011.11.21 FALSE   1
12383 2011.11.21 NA 2011.11.21 FALSE   1
12384 2011.11.21 NA 2011.11.21 FALSE   1
12385 2011.11.21 NA 2011.11.21 FALSE   1
12386 2011.11.21 NA 2011.11.21 FALSE   1
12387 2011.11.21 NA 2011.11.21 FALSE   1
12388 2011.11.21 NA 2011.11.21 FALSE   1
12389 2011.05.16 NA 2011.05.16 FALSE   1
12390 2011.05.16 NA 2011.05.16 FALSE   1

In [ ]:
atpD <- atp %>% 
    separate_wider_delim(Date, " - ", names=c("ds", "df"), too_few = "align_start") %>% 
    mutate(tournament.date_start = ymd(ds), tournament.date_finish = ymd(df)) %>%
    select(-ds, -df) %>%
    mutate(tournament.duration = ifelse(
        tournament.date_finish %>% is.na(),
        0,
        tournament.date_finish - tournament.date_start
    ))

In [ ]:
options(scipen=999)
atpD %>% group_by(tournament.duration) %>% summarise(n=n(), freq = n/nrow(atpD)*100) %>% arrange(-n)

   tournament.duration n       freq
1      6               1144856 87.4713772171
2     13                118095  9.0229096869
3      5                 29228  2.2331309905
4      0                 12445  0.9508455993
5      7                  1672  0.1277471950
6     14                   988  0.0754869789
7     20                   306  0.0233795704
8      9                   236  0.0180313026
9     12                   231  0.0176492835
10    27                   180  0.0137526885
11    11                   162  0.0123774196
12     8                   137  0.0104673240
13     2                   108  0.0082516131
14    -1                    63  0.0048134410
15     4                    54  0.0041258065
16     3                    30  0.0022921147
17    17                    25  0.0019100956
18    10                     9  0.0006876344
19    48                     6  0.0004584229
20 -3646                     4  0.0003056153

TODO analise disto

In [ ]:
# todo ainda n ta acabado